### ISSUE TITLE
[Blog] Add translation doc in English for PouchContainer technology blogs

### ISSUE THREAD

**Issue by Starnop** [pouchcontainer/blog#24]
Please Add translation doc in English for PouchContainer technology blogs, the docs are:

Team1/2: [深度解析 PouchContainer 的富容器技术.md](https://github.com/pouchcontainer/blog/blob/master/blog-cn/%E6%B7%B1%E5%BA%A6%E8%A7%A3%E6%9E%90PouchContainer%E7%9A%84%E5%AF%8C%E5%AE%B9%E5%99%A8%E6%8A%80%E6%9C%AF.md)
Team3/4: [深入解析 PouchContainer 如何实现容器原地升级](https://github.com/pouchcontainer/blog/blob/master/blog-cn/%E6%B7%B1%E5%85%A5%E8%A7%A3%E6%9E%90%20PouchContainer%20%E5%A6%82%E4%BD%95%E5%AE%9E%E7%8E%B0%E5%AE%B9%E5%99%A8%E5%8E%9F%E5%9C%B0%E5%8D%87%E7%BA%A7.md)
Team5/6: [PouchContainer volume机制解析.md](https://github.com/pouchcontainer/blog/blob/master/blog-cn/PouchContainer%20volume%E6%9C%BA%E5%88%B6%E8%A7%A3%E6%9E%90.md)
Team7/8: [PouchContainer Goroutine Leak 检测实践.md](https://github.com/pouchcontainer/blog/blob/master/blog-cn/PouchContainer%20Goroutine%20Leak%20%E6%A3%80%E6%B5%8B%E5%AE%9E%E8%B7%B5.md)
Team9/10: [PouchContainer-支持-LXCFS-实现高可靠容器隔离.md](https://github.com/pouchcontainer/blog/blob/master/blog-cn/PouchContainer-%E6%94%AF%E6%8C%81-LXCFS-%E5%AE%9E%E7%8E%B0%E9%AB%98%E5%8F%AF%E9%9D%A0%E5%AE%B9%E5%99%A8%E9%9A%94%E7%A6%BB.md)

Additional doc: 
[PouchContainer CRI的设计与实现.md](https://github.com/pouchcontainer/blog/blob/master/blog-cn/PouchContainer%20CRI%E7%9A%84%E8%AE%BE%E8%AE%A1%E4%B8%8E%E5%AE%9E%E7%8E%B0.md) 

The paragraphs are grouped as follows:
Team1/2: Paragraph  1
Team3/4: Paragraph 2 and Paragraph 3
Team5/6: Paragraph 4
Team7/8: Paragraph 5
Team9/10: Paragraph 6

Please add origin doc link in your translation doc and put the docs into blog_en folder.

**Comment by zl117** [comment]
#27 
Group 1 has pushed our solutions to the second problem and our thinking
